version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    target-branch: "features"
    schedule:
      interval: "daily"
    groups:
      dependencies:
        patterns:
          - "*"
